import { defineConfig } from "oxlint"

export default defineConfig({
  options: {
    denyWarnings: true,
    reportUnusedDisableDirectives: "error",
    typeAware: true,
    typeCheck: true,
  },
  plugins: [
    "typescript",
    "import",
    "react",
    "react-perf",
    "jsx-a11y",
    "promise",
    "unicorn",
    "node",
  ],
  categories: {
    correctness: "warn",
    suspicious: "warn",
    pedantic: "warn",
    perf: "warn",
    style: "warn",
  },
  rules: {
    "typescript/no-explicit-any": "warn",
    "typescript/no-non-null-assertion": "warn",
    "typescript/no-require-imports": "warn",
    "typescript/no-var-requires": "warn",
    "typescript/no-import-type-side-effects": "warn",
    "typescript/no-non-null-asserted-nullish-coalescing": "warn",
    "typescript/use-unknown-in-catch-callback-variable": "warn",
    "import/no-cycle": "warn",
    "import/no-commonjs": "warn",
    "import/max-dependencies": "off",
    "no-eval": "warn",
    "no-var": "warn",
    eqeqeq: "warn",
    // Guard clauses are intentionally concise; braces do not improve their control flow.
    curly: "off",
    // Explicit branch termination keeps event and message handlers easy to audit.
    "no-useless-return": "off",
    "react/only-export-components": "warn",
    "react/no-danger": "warn",
    "react/no-unknown-property": "warn",
    "react/button-has-type": "warn",
    "unicorn/prefer-node-protocol": "warn",
    "unicorn/prefer-module": "warn",
    // Browser-specific globals document which runtime owns event listeners and dispatch.
    "unicorn/prefer-global-this": "off",
    // Typed-array slice preserves the source container and backing-buffer semantics.
    "unicorn/prefer-spread": "off",
    // Scientific fixtures already group values by their domain representation.
    "unicorn/numeric-separators-style": "off",
    "typescript/no-floating-promises": ["warn", { ignoreVoid: true }],
    "promise/always-return": ["warn", { ignoreLastCallback: true }],
    "no-console": ["warn", { allow: ["info", "warn", "error"] }],
    "no-unused-vars": "off",
    "no-duplicate-imports": ["warn", { allowSeparateTypeImports: true }],
    "typescript/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
    "react/react-in-jsx-scope": "off",
    "react/jsx-filename-extension": "off",
    "no-magic-numbers": "off",
    "no-ternary": "off",
    "no-nested-ternary": "off",
    "sort-keys": "off",
    "sort-imports": "off",
    "func-style": "off",
    "max-lines": "off",
    "max-lines-per-function": "off",
    "max-statements": "off",
    "max-params": "off",
    "max-depth": "off",
    "no-undefined": "off",
    "no-void": "off",
    "no-use-before-define": "off",
    "no-await-in-loop": "off",
    "no-plusplus": "off",
    "no-bitwise": "off",
    "no-continue": "off",
    "no-inline-comments": "off",
    "no-param-reassign": "off",
    "no-underscore-dangle": "off",
    "prefer-destructuring": "off",
    "id-length": "off",
    "capitalized-comments": "off",
    "init-declarations": "off",
    "import/exports-last": "off",
    "import/group-exports": "off",
    "import/prefer-default-export": "off",
    "import/no-default-export": "off",
    "import/no-named-export": "off",
    "import/no-unassigned-import": "off",
    "import/no-nodejs-modules": "off",
    "import/no-anonymous-default-export": "off",
    "typescript/explicit-function-return-type": "off",
    "typescript/explicit-module-boundary-types": "off",
    "typescript/prefer-readonly-parameter-types": "off",
    "typescript/explicit-member-accessibility": "off",
    "typescript/no-empty-object-type": "off",
    "typescript/no-namespace": "off",
    "typescript/method-signature-style": "off",
    // noPropertyAccessFromIndexSignature requires bracket access for environment variables.
    "typescript/dot-notation": "off",
    "unicorn/no-array-callback-reference": "off",
    "unicorn/prefer-query-selector": "off",
    "unicorn/switch-case-braces": "off",
    "unicorn/no-null": "off",
    "unicorn/filename-case": "off",
    "unicorn/no-array-for-each": "off",
    "unicorn/no-array-reduce": "off",
    "unicorn/no-process-exit": "off",
    "unicorn/no-nested-ternary": "off",
    "unicorn/consistent-function-scoping": "off",
    "unicorn/no-useless-undefined": "off",
    "react/jsx-max-depth": "off",
    "react/no-multi-comp": "off",
    "react/jsx-props-no-spreading": "off",
    "react/forbid-component-props": "off",
    "react/forbid-dom-props": "off",
    "react/prefer-function-component": "off",
    "react/jsx-handler-names": "off",
    "promise/prefer-await-to-then": "off",
    "promise/prefer-await-to-callbacks": "off",
    "promise/avoid-new": "off",
  },
  overrides: [
    {
      files: ["**/*.d.ts"],
      rules: {
        "typescript/no-explicit-any": "off",
        "typescript/no-unused-vars": "off",
        "typescript/consistent-type-imports": "off",
      },
    },
    {
      files: ["src/auspice-client/bridge.ts", "src/viewerManager.ts"],
      rules: {
        // These files use VS Code's one-argument postMessage APIs, not Window.postMessage.
        "unicorn/require-post-message-target-origin": "off",
      },
    },
    {
      files: ["test/**/*.ts"],
      rules: {
        // Bun's asynchronous rejection matchers are not modeled by tsgolint.
        "typescript/await-thenable": "off",
        "typescript/no-confusing-void-expression": "off",
      },
    },
    {
      files: ["test/__tests__/test_prop_newick_conversion.test.ts"],
      rules: {
        // fast-check documents its default namespace as its primary API.
        "import/no-named-as-default-member": "off",
      },
    },
  ],
})
